# Generated by Django 5.0.7 on 2024-07-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obituary_platform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obituary',
            old_name='contet',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='obituary',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
